# This file was generated by GoReleaser. DO NOT EDIT.
cask "claude-runway" do
  version "0.4.1"

  on_macos do
    on_intel do
      sha256 "a5560df7168e731ea28c6e99c84606c4741d02d4e2d3c0fb80d35e32135f0c6d"
      url "https://github.com/tenex-hq/claude-runway/releases/download/v#{version}/claude-runway_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "a54573478a5fe8ddfb1130bd0f6c1ce7c23f8a17203e30833eda875b05ec7042"
      url "https://github.com/tenex-hq/claude-runway/releases/download/v#{version}/claude-runway_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "bbc9818ac652246fb52016f1a8101800ab88fc75879eecf09bfdad964f98b1dc"
      url "https://github.com/tenex-hq/claude-runway/releases/download/v#{version}/claude-runway_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "428a5fe5c67d8214d0ea5c1ce4e69a4a2cd6816eb8697f6aa60052e00d49dc99"
      url "https://github.com/tenex-hq/claude-runway/releases/download/v#{version}/claude-runway_#{version}_linux_arm64.tar.gz"
    end
  end

  name "claude-runway"
  desc "How much of your Claude subscription allowance is left, and whether it will last to the reset"
  homepage "https://github.com/tenex-hq/claude-runway"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "claude-runway"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/claude-runway"],
                     must_succeed: false
    end
  end

  # No zap stanza required

end
