# This file was generated by GoReleaser. DO NOT EDIT.
cask "claude-runway" do
  version "0.4.0"

  on_macos do
    on_intel do
      sha256 "549690eb1529ae7d95bf71b96747876cab52631d6339c08c4551409d506f19ac"
      url "https://github.com/tenex-hq/claude-runway/releases/download/v#{version}/claude-runway_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "d0b41d1f927e877634edb64a9a75b7e20f3907e5c81334e370ddf20a9d8e7253"
      url "https://github.com/tenex-hq/claude-runway/releases/download/v#{version}/claude-runway_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "a753da6c660c998a8546ae723f87dcc078ee7b50ec6553868c775e0fb25caf65"
      url "https://github.com/tenex-hq/claude-runway/releases/download/v#{version}/claude-runway_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "3412583db5fbb91625329bba0c46b9fee354810b74751f2790391df8501b8efa"
      url "https://github.com/tenex-hq/claude-runway/releases/download/v#{version}/claude-runway_#{version}_linux_arm64.tar.gz"
    end
  end

  name "claude-runway"
  desc "How much of your Claude subscription allowance is left, and whether it will last to the reset"
  homepage "https://github.com/tenex-hq/claude-runway"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "claude-runway"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/claude-runway"],
                     must_succeed: false
    end
  end

  # No zap stanza required

end
