# This file was generated by GoReleaser. DO NOT EDIT.
cask "claude-runway" do
  version "0.2.1"

  on_macos do
    on_intel do
      sha256 "29b4e5da5a0021fd9d311e30040c612d0db457bc0be80076792cebab516dd165"
      url "https://github.com/tenex-hq/claude-runway/releases/download/v#{version}/claude-runway_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "478a0bf8092931a583d96a3214895cccadfea710cdbcbae3e74b560126212cf7"
      url "https://github.com/tenex-hq/claude-runway/releases/download/v#{version}/claude-runway_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "31e6b9ae0102c9cb72556c865d7f672fa412faddf1f82ea4c55390c861c1bd1d"
      url "https://github.com/tenex-hq/claude-runway/releases/download/v#{version}/claude-runway_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "381a5f6deca7a60435785740bb24031a5137504fe37bdac622039ea899bf3114"
      url "https://github.com/tenex-hq/claude-runway/releases/download/v#{version}/claude-runway_#{version}_linux_arm64.tar.gz"
    end
  end

  name "claude-runway"
  desc "How much of your Claude subscription allowance is left, and whether it will last to the reset"
  homepage "https://github.com/tenex-hq/claude-runway"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "claude-runway"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/claude-runway"],
                     must_succeed: false
    end
  end

  # No zap stanza required

end
